config/routes.rb
Rails.application.routes.draw do
  root to: "party_host#index"
  namespace :admin do
    resources :users
    resources :guests
    resources :invitations
    resources :parties
    root to: "users#index"
  end

  devise_for :users
  resources :party_host, only: [:index]
  resources :flyer, only: [:index]
  resources :guests
  resources :invitations, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/guest.rb
class Guest < ApplicationRecord
  belongs_to :party
  has_one :invitation

  def magic_link


  end
end

app/models/invitation.rb
require "securerandom"

class Invitation < ApplicationRecord
  belongs_to :guest

  def self.create_for(guest)
    invitation = new(guest: guest)
    invitation.secret_id = SecureRandom.uuid
    invitation.save!
		InvitationMailer.new_invitation(guest).deliver_now
  end

  def self.resend_to_all_no_responses
    Party.first.guests.where(going: false).each do |guest|
      InvitationMailer.new_invitation(guest).deliver_now
    end
  end
end

app/models/party.rb
class Party < ApplicationRecord
  has_many :guests
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :trackable, :validatable
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_action :authenticate_admin

    def authenticate_admin
      redirect_to root_path unless current_user.admin?
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/admin/guests_controller.rb
module Admin
  class GuestsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Guest.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Guest.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/invitations_controller.rb
module Admin
  class InvitationsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Invitation.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Invitation.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/parties_controller.rb
module Admin
  class PartiesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Party.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Party.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = User.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   User.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
	before_action :authenticate_user!
end

app/controllers/flyer_controller.rb
class FlyerController < ApplicationController
  def index
  end
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:update]

  def create
    @guest = Guest.new(guest_params)

    if @guest.save
      Invitation.create_for(@guest)
      redirect_to party_host_index_path, notice: 'Guest was added'
    else
      redirect_to party_host_index_path, alert: 'error'
    end
  end

  def update
    guest = Guest.find_by!(id: params[:id])
    guest.going = params[:guest][:going]
    guest.save!
    redirect_to invitation_path(guest.invitation.secret_id), alert: 'error'
  end

  private

  def guest_params
    params.require(:guest).permit(:name, :email, :party_id)
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show]
  # before_action :set_invitation, only: [:edit, :update, :destroy]

  # GET /invitations
  # GET /invitations.json
  # def index
  #   @invitations = Invitation.all
  # end

  # GET /invitations/1
  # GET /invitations/1.json
  def show
    @invitation = Invitation.find_by!(secret_id: params[:id])
    @guest = @invitation.guest
  end

  # GET /invitations/new
  # def new
  #   @invitation = Invitation.new
  # end

  # # GET /invitations/1/edit
  # def edit
  # end

  # # POST /invitations
  # # POST /invitations.json
  # def create
  #   @invitation = Invitation.new(invitation_params)

  #   respond_to do |format|
  #     if @invitation.save
  #       format.html { redirect_to @invitation, notice: 'Invitation was successfully created.' }
  #       format.json { render :show, status: :created, location: @invitation }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @invitation.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # PATCH/PUT /invitations/1
  # # PATCH/PUT /invitations/1.json
  # def update
  #   respond_to do |format|
  #     if @invitation.update(invitation_params)
  #       format.html { redirect_to @invitation, notice: 'Invitation was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @invitation }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @invitation.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # DELETE /invitations/1
  # # DELETE /invitations/1.json
  # def destroy
  #   @invitation.destroy
  #   respond_to do |format|
  #     format.html { redirect_to invitations_url, notice: 'Invitation was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  # private
  #   # Use callbacks to share common setup or constraints between actions.
  #   def set_invitation
  #     @invitation = Invitation.find(params[:id])
  #   end

  #   # Never trust parameters from the scary internet, only allow the white list through.
  #   def invitation_params
  #     params.require(:invitation).permit(:secret_id, :belongs_to)
  #   end
end

app/controllers/party_host_controller.rb
class PartyHostController < ApplicationController
  def index
    @guest = Guest.new
  end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flyer_helper.rb
module FlyerHelper
end

app/helpers/invitation_helper.rb
module InvitationHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/party_host_helper.rb
module PartyHostHelper
end

app/views/flyer/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <main class="outer-container">
      <%= image_tag("disco-ball.gif") %>
      <h1 class="party-font">Groovytime</h1>
      <%= image_tag("dancefloor.gif") %>
      </main>
    </div>
  </div>
</div>

app/views/invitations/_form.html.erb
<%= form_with(model: invitation, local: true) do |form| %>
  <% if invitation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(invitation.errors.count, "error") %> prohibited this invitation from being saved:</h2>

      <ul>
      <% invitation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :secret_id %>
    <%= form.text_field :secret_id, id: :invitation_secret_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/invitations/edit.html.erb
<h1>Editing Invitation</h1>

<%= render 'form', invitation: @invitation %>

<%= link_to 'Show', @invitation %> |
<%= link_to 'Back', invitations_path %>

app/views/invitations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Invitations</h1>

<table>
  <thead>
    <tr>
      <th>Secret</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @invitations.each do |invitation| %>
      <tr>
        <td><%= invitation.secret_id %></td>
        <td><%= link_to 'Show', invitation %></td>
        <td><%= link_to 'Edit', edit_invitation_path(invitation) %></td>
        <td><%= link_to 'Destroy', invitation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Invitation', new_invitation_path %>

app/views/invitations/new.html.erb
<h1>New Invitation</h1>

<%= render 'form', invitation: @invitation %>

<%= link_to 'Back', invitations_path %>

app/views/invitations/show.html.erb
<div class="invitation-container">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 controls">
        <audio class="pull-right" controls autoplay>
          <source src="/jungle.mp3"> </source>
        </audio>
      </div>
    </div>
      <div class="force-left text-center animated slideInUp">
          <% party = @guest.party %>
          <h3 class="animated flash">Hey <%= @guest.name.chomp %>!</h3>
          <h3> You are invited to the <%= party.title %></h3>

          <p><%= party.description %>         </p>
          <p><b>Starts at:</b>   <%= party.start_time.strftime("%A, %B %d, %I:%M:%S, %Y")  %>          </p>
          <p><b>Location:</b>     <%= party.location %>            </p>
          <p><b>Contact info:</b> <%= party.contact_information %> </p>
        <% if @guest.going? %>
          <h2>See you there!</h2>
          <br>

          <small>Need to changed your mind?</small>
        <%= form_for(@guest) do |form| %>
          <% if @guest.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@guest.errors.count, "error") %> prohibited this invitation from being saved:</h2>
              <ul>
                <% @guest.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <div class="field">
            <%= form.hidden_field :going, value: 0 %>
          </div>

          <div class="actions">
            <%= form.submit "I can't make it now", class: "btn btn-xs btn-danger" %>
          </div>
        <% end %>
        <% else %>
        <h1>Are You In?</h1>
          <%= form_for(@guest) do |form| %>
            <% if @guest.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@guest.errors.count, "error") %> prohibited this invitation from being saved:</h2>
                <ul>
                  <% @guest.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>

            <div class="field">
              <%= form.hidden_field :going, value: 1%>
            </div>

            <div class="actions">
              <%= form.submit "Yes", class: "btn btn-lg btn-success"  %>
            </div>
          <% end %>
        <br>

        <%= form_for(@guest) do |form| %>
          <% if @guest.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@guest.errors.count, "error") %> prohibited this invitation from being saved:</h2>
              <ul>
                <% @guest.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <div class="field">
            <%= form.hidden_field :going, value: 0 %>
          </div>

          <div class="actions">
            <%= form.submit "No", class: "btn btn-xs btn-danger" %>
          </div>
        <% end %>
        <% end %>
      </div>

    <div class="row">
      <div class="col-lg-12">
        <%= image_tag("disco-ball.gif", size: "450x450", class: "center-block animated fadeIn disco-ball") %>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-2"></div>
      <div class="col-lg-8 img-box">
        <%= image_tag("violet2.png", id: "violet2", size:"300x400", class: "img-rounded animated fadeInRightBig pull-left") %>
        <%= image_tag("violet1.png", id: "violet1", size:"300x400", class: "img-rounded animated fadeInLeftBig pull-right") %>
      </div>
      <div class="col-lg-2"></div>
    </div>

    <div class="row dance-floor">
      <div class="col-lg-12">
        <%= image_tag("dancefloor.gif", class: "center-block") %>
      </div>
    </div>

</div>
</div>

app/views/party_host/index.html.erb
<% party = Party.first %>
<% if notice %>
  <p class="alert alert-info notice"><%= notice %></p>
<% end %>

<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <br>
      <%= link_to "Admin Panel", admin_users_path, class: "btn btn-primary pull-right"%>

      <%= mail_to party.guests.map(&:email).join(","),
        "Email All the Guests",
        subject: party.title,
        class: "btn btn-primary pull-right"
      %>

      <%= mail_to party.guests.where(going: :false).map(&:email).join(","),
        "Email All No",
        subject: party.title,
        class: "btn btn-primary pull-right"
      %>

      <%= mail_to party.guests.where(going: :true).map(&:email).join(","),
        "Email All Yes",
        subject: party.title,
        class: "btn btn-primary pull-right"
      %>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <h1>Parties</h1>
      <hr />
      <ol>
        <li>
          <% if party %>
            <div class="well">
              <h4><%= party.title %></h4>
              <p><b>Description:</b>  <%= party.description %>         </p>
              <p><b>Start time:</b>   <%= party.start_time %>          </p>
              <p><b>End time:</b>     <%= party.end_time %>            </p>
              <p><b>Location:</b>     <%= party.location %>            </p>
              <p><b>Contact info:</b> <%= party.contact_information %> </p>
            </div>

            <div class="well">
              <h4>RSVP counts</h4>
              <p>
                Yes: <span class="label label-success"><%= party.guests.where(going: true).count %> </span>
              </p>
              <p>
                No:  <span class="label label-danger"><%= party.guests.where(going: false).count %></span>
              </p>
            </div>

            <div class="well">
              <h4>Guests</h4>
              <ol>
                <% party.guests.each do |guest| %>
                  <li>
                    <b><%= guest.name %>, <%= guest.email %></b>,
                    <span class="label <%= guest.going? ? "label-success" : "label-danger" %>"><%= if guest.going? then "Yes" else "No" end %></span>
                    <div>
                      <small>invite link:</small>
                      <% link = LinkBuilder.new(guest).magic_link %>
                      <%= link_to link, link %>
                    </div>
                  </li>
                <% end %>
              </ol>
            </div>

            <div class="well">
              <h4>Add a guest</h4>
              <%= form_for(@guest) do |form| %>
                <% if @guest.errors.any? %>
                  <div id="error_explanation">
                    <h2><%= pluralize(@guest.errors.count, "error") %> prohibited this guest from being saved:</h2>

                    <ul>
                      <% @guest.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                      <% end %>
                    </ul>
                  </div>
                <% end %>

                <div class="field">
                  <%= form.label :name %>
                  <%= form.text_field :name, required: true %>
                </div>

                <div class="field">
                  <%= form.label :email %>
                  <%= form.email_field :email, required: true %>
                </div>

                <%= form.hidden_field :party_id, value: party.id %>

                <div class="actions">
                  <%= form.submit "Add Guest", class: "btn btn-primary" %>
                </div>
              <% end %>


            </div>
          <% end %>
        </li>
      </ol>
    </div>
  </div>
</div>